### ISSUE TITLE
Gesamtverbrauch /Total Consumption Fakegato Graph

### ISSUE THREAD

**Issue by Mart-Muc** [produdegr/homebridge-3em-energy-meter#10]
Actually I love that graphbar…. But it’s not very intuitiv:

It shows the energy used in 10 minutes (unit: Wh)

A) why is this bargraph a child to total consumption? Its not the integration about the whole time but only 10min timeframe

B) actually it would me more intuitiv to see the average power in this timeframe.(to compare it to the values from the appliances)

—> can you please save 10 measurements/h instead of 6 for fakegato( e.g. 6min timeframes). then the user can just multiply the value of the graph with 10/h and get easily the average power in this timeframe

—> or more intuitive and physical correct: move the graph to Consumption and change the units to W. 
So it gets a box-plot: height is the power, area is the Energy

PS: is there a parameter to reset the total Energy Consumption?

**Comment by produdegr** [comment]
Dear Mart-Muc, you sound like you bought something but did not like it in the end. Too Bad.
Well just kidding, there is a reason why things are like they are, This is a plugin that takes values from the Shelly product and tries to make them work in the EVE app. Both things are out of my control and I can only implement things I can use.
If you would be so kind to read past "issues" you would read that the reset of the Energy Consumption has to happen in the Shelly Software - this is just a plug, agreed?
