### ISSUE TITLE
No negative Values with 1.1.2 

### ISSUE THREAD

**Issue by thechris1992** [produdegr/homebridge-3em-energy-meter#11]
Hey,

with 1.1.0 the Consumption stops at 0.
I got negative Values (PV Power :D )

with V1.1.2 the spend / negative values -X Watt will be show in positive values.
 
 Can you display negative values or can you add a checkbox for „stop at 0 W“?

workaround for me: use V1.1.0

**Comment by thechris1992** [comment]
index.js erweitert:

this.powerConsumption = (parseFloat(json.emeters[0].power)+parseFloat(json.emeters[1].power)+parseFloat(json.emeters[2].power));
                **if (this.powerConsumption < 0) { this.powerConsumption = 0 };**
				this.totalPowerConsumption = ((parseFloat(json.emeters[0].total)+parseFloat(json.emeters[1].total)+parseFloat(json.emeters[2].total))/1000);
                **if (this.totalPowerConsumption < 0) { this.totalPowerConsumption = 0 };**
			    this.voltage1 = (((parseFloat(json.emeters[0].voltage)+parseFloat(json.emeters[1].voltage)+parseFloat(json.emeters[2].voltage))/3));
				this.ampere1 = (((parseFloat(json.emeters[0].current)*this.pf0)+(parseFloat(json.emeters[1].current)*this.pf1)+(parseFloat(json.emeters[2].current)*this.pf2)));
                **if (this.ampere1 < 0) { this.ampere1 = 0 };**

**Comment by produdegr** [comment]
Sorry for my very late reply.
So you need that all negative values to be zeroed, right?
If I implement:    Negative Values Handling -> Option 1. Zero Values, Option 2. Show Absolute (positive) Values
Are you covered?

**Comment by produdegr** [comment]
Please try new version and report back. Thank You.

**Comment by thechris1992** [comment]
works like charm, thanks!

**Comment by thechris1992** [comment]
Closed with V1.1.3
