### ISSUE TITLE
showing total kWh instead of current consumption in W in glances

### ISSUE THREAD

**Issue by fate8383** [produdegr/homebridge-3em-energy-meter#15]
Amazing plugin, I cannot thank you enough. I have just noticed this issue and I cannot get it corrected. I am new to the shelly 3em, working great and with your plugin I can see in EVE app all I need. Except, up until today in the EVE Glances view it was showing current total consumption in Watts, which is great that I can see current Watt usage but as of today it started showing total consumption in kWh like electric meter shows. I don't really need this info in the glances, but current usage in Watts is really useful. I tried all possible options in EVE app to switch it back but I cannot succeed. I am also exporting to prometheus for historical data I noticed my total kWh passed 80kwh and it turned to red in the graphs, this is I think default behavior for all on/off switches like >80 turns red, I suspect it has something to the with that, but I might be completely wrong. I of course easily changed the based coloring in the grafana but Eve app showing by default just total KWH in glances is not something I can change. Any comments? advice?

**Comment by fate8383** [comment]
Couple of reboots and now it shows total A ampere in the glances...strange that I don't get to choose which one to show there, maybe it is eve app issue? Or I don't have where I am looking at :)

**Comment by produdegr** [comment]
I have no control over the EVE app, neither do I know how to change what glances show in it.
Sorry.

**Comment by fate8383** [comment]
thanks for reply, I really don't know either. it picks up random I guess, I have no idea it came up as total KWH after a week and then Ampere after a day and now it is stuck in Ampere no matter what I do I cannot change the default to watts instead of A 
![Screenshot 2023-02-09 at 4 15 15 PM](https://user-images.githubusercontent.com/17381874/217853147-99e63a30-8193-45e3-8803-9d24f7266c65.png)
