### ISSUE TITLE
Reste Power measurement (EVE App)

### ISSUE THREAD

**Issue by YvesSun23** [produdegr/homebridge-3em-energy-meter#16]
Hi,

I use the 3em directly at the house connection box to record the total energy consumption.
Now the new billing period is starting and I would like to start from zero.
How can I reset or restart the Power measurement (history) in the eve app?
Do I have to reset the 3em completely?

Greetings YS

**Comment by produdegr** [comment]
Hi,

You must do that in the Shelly 3EM web interface or the Shelly app.

**Comment by YvesSun23** [comment]
Thank you for the quick reply, it worked :)
And thanks for the plugin, I like it very much.
