### ISSUE TITLE
5 Shellys EM work in total consumption calculation but history is same for 4, 1 correct ??

### ISSUE THREAD

**Issue by megabyte0469** [produdegr/homebridge-3em-energy-meter#18]
Hello, have here 5 Shellys EM. Setup works so far. All 5 Shellys show different current values, power values, total power values and total cost. So far everything seems to be ok. Only with the history there seems to be a problem. 4 of the 5 Shellys show the same history only one of the 5 shows the correct history to its power or consumption values. Each Shelly em has received its own port address from the Homebridge. If you want me to post the configuration here then please report.

here some log data

[3/10/2023, 5:08:28 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 3B56) is running on port 51340.
[3/10/2023, 5:08:29 AM] [Energy Meter] Launched child bridge with PID 3717
[3/10/2023, 5:08:29 AM] [Energy Meter Solar] Launched child bridge with PID 3723
[3/10/2023, 5:08:29 AM] [Phase 3] Launched child bridge with PID 3742
[3/10/2023, 5:08:29 AM] [Phase 1] Launched child bridge with PID 3729
[3/10/2023, 5:08:29 AM] [Phase 2] Launched child bridge with PID 3736

<img width="1281" alt="Bildschirm­foto 2023-03-10 um 05 20 23" src="https://user-images.githubusercontent.com/63038422/224225372-ae6b8008-9a33-444d-8770-a95e3f35cf65.png">

<img width="1279" alt="Bildschirm­foto 2023-03-10 um 05 44 40" src="https://user-images.githubusercontent.com/63038422/224225573-f626acb0-117a-4a74-b4c1-b283a4d24977.png">

**Comment by produdegr** [comment]
Sorry for late reply.
The plugin was build for 3EM and as such only for one instance.
Multiple instances might work, but History aparently will not (because it takes the name of the plugin to store data).
I currently have not the resources to make the plugin work with multiple instances.
