### ISSUE TITLE
Help to understand real consumation 

### ISSUE THREAD

**Issue by santiagos5** [produdegr/homebridge-3em-energy-meter#19]
Hello, 

Eve app show me: 860wh as consumation in a day. 
If my device consume 6wh every 10 minute (misure 6 Times at hour, see logs) for 24 hours= 864 wh at day, but the interval “6wh every 10 minute (misure 6 Times at hour)” is not equal to 6wh? —> (6wh x 6 Times /6 records) and the total consumtion equal to 6wh x 24h= 144wh?

The device used for test is a heat pump but it is always power off, only main controller is power on and with the display always with screen off. 0,864kwh at day seems to be more..

![IMG_9431](https://user-images.githubusercontent.com/35889101/235513281-b7f83409-811e-4bdd-962a-8d5aebebddb0.png)
![IMG_9432](https://user-images.githubusercontent.com/35889101/235513268-f0d6f4c1-a393-4f82-8aa9-c385232de961.png)

**Comment by produdegr** [comment]
I simply get the values from the 3EM device via API and they re then used by the EVE app. No control of what EVE app does with them or why.
