### ISSUE TITLE
Current values

### ISSUE THREAD

**Issue by nofear77** [produdegr/homebridge-3em-energy-meter#2]
Hello produdegr,

I noticed that the current values do not match the power values. Is it possible to adjust the values according to the formula?
(Current Phase A) x (Power Factor Phase A) + (Current Phase B) x (Power Factor Phase B) + (Current Phase C) x (Power Factor Phase C) = Total Current

for comparison see picture
0.98A x 0.33 + 1.08A x 0.74 + 0.71A x 0.54 = 1.506A

Voltage average
(voltage phase A + voltage phase B + voltage phase C) / 3 = voltage average value
(227V + 228V + 230V) / 3 = 228.33V

Power (for verification)
Total current x voltage average = power
1.506A x 228.33V = 344W

With these formulas, the values defend plausible.
![IMG_0050](https://user-images.githubusercontent.com/62308854/115119919-1118e400-9fab-11eb-8e3f-cbba536c1890.jpg)

**Comment by produdegr** [comment]
The current values are given as reported by shelly api. A "Total Current" is in fact a plasmatic number without meaning. Of course do you need to multiply by power factor each current to match the "Total Current" and the total Consumption. However it would make sense if you would have real 3 phase equippment ( 3 phase motor ) where the term "Total Current" would make some sense. For eaxample if all phases are on 2 Amps, then all current is 2 Amps througout. I supplied the "Ttotal Current" as a simple accumulation having in mind a simple logic when having for example a 2 Amps single phase device on one phase and moving it to another phase it still would show 2 Amps. So the total value can be seen as an accumulation of signature Amps (there exists AI algorythms that self-learn what devices there are in your house). That is the reason why I did not incorporate the pf. 
Anyhow, if you should have 3 phase devices and therfor a real meaning to "Total Current" or want it to be shown this way,, will I  implement it in the next realease, maybe with an option in the config.

Ideally would be to show 3 Voltages, 3 Amps, 3 power factors and 3 pf values, just as shelly does amd provides with the API.

**Comment by nofear77** [comment]
Displaying 3x current / voltage / power factor would be good, but unfortunately it is not supported by the EVE app. Therefore I would be happy if you can implement it that way (also as an option).
Many thanks in advance.

**Comment by produdegr** [comment]
V0.1.3 release where you can enable pf usage (default is disabled).
