### ISSUE TITLE
Estimate cost and total cost shows zero

### ISSUE THREAD

**Issue by fate8383** [produdegr/homebridge-3em-energy-meter#20]
Last few days it is showing zero on those values, would this be regional cost link is broken on plugin or eve app problem? Thanks

**Comment by produdegr** [comment]
EVE app -> Settings -> General -> Energy Cost -> Electricity Rate. Check if it's filled out.
They must have changed stuff because my value disappeared as well.

**Comment by fate8383** [comment]
I don't even have it there :) I am not sure maybe I have nothing eve energy meter device or something but literally all my searches leads to this setting but I have nothing like that there. Am I missing something?

**Comment by fate8383** [comment]
Honestly, there is no solution to this? I miss estimated cost...

**Comment by fate8383** [comment]
Wow just a min after I wrote a new version of eve app came to public and it is fixed.
