### ISSUE TITLE
iOS 18 support for Energy Monitoring

### ISSUE THREAD

**Issue by 350d** [produdegr/homebridge-3em-energy-meter#23]
Hello! Any plans or progress to update plugin with latest iOS updates for energy monitoring?
Looking forward for support this awesome feature!

**Comment by produdegr** [comment]
There are no plans by Apple to support energy monitoring in Homekit, freely. They are talking for iOS 18 about supporting energy company's devices specifically and this only in the US.
Should they start to support it in any way, however, there are no changes needed in the plugin. Homekit will start showing all data as EVE does already today.
