### ISSUE TITLE
3EM has 3 channels not  2

### ISSUE THREAD

**Issue by rionshin** [produdegr/homebridge-3em-energy-meter#24]
@produdegr  3EM has 3 channels not two - so in settings you should allow to have 0 , 1,2,3 also when you combine the readings for total consumption you combine channel one and two but do not combine  3 to it. 

For example my  accumulated consumption is like:
Channel 1 (Phase 1): 1.1Mwh
Channel 2 (Phase 2): 1.8 MWh 
Channel   3 (Phase 3): 600kWh 

In EVE app i am seeing 2900kwh and phase  3 consumption is missing. 

could you please fix it and show overall readings  and moment reading correctly ?

Shelly EM is 2 channels: https://www.shelly.com/en-us/products/shop/shelly-em-120a
Shelly 3EM is 3 channels:   https://www.shelly.com/en-bg/products/shop/shelly-3-em

<img width="972" alt="Screenshot 2024-08-19 at 22 44 47" src="https://github.com/user-attachments/assets/2371dbfd-0c3a-4de3-a877-882220437a29">

**Comment by produdegr** [comment]
What makes you think that this plugin only uses two channels?
I suggest you read the documentation and especially the configuration variables "use_em" and "use_em_mode".
I suppose you have "use_em" = true, which in your case is wrong. These setting are used if you have a shelly EM and not 3EM.

**Comment by rionshin** [comment]
I am sorry , I really misread the help. All is ok
