### ISSUE TITLE
Just question about iOS 18 HomeKit electric measure feature

### ISSUE THREAD

**Issue by fate8383** [produdegr/homebridge-3em-energy-meter#26]
Will this be working in HomeKit iOS 18 out of the box as we feed with the plugin HomeKit but only able to see it in EVE app for now? Just curiosity, I cannot find any definitive answer out of there online. We are few bunch happily using EVE app with Shelly 3em :) maybe you tried with iOS 18 beta or something...

Thanks

**Comment by produdegr** [comment]
https://github.com/produdegr/homebridge-3em-energy-meter/issues/23

**Comment by fate8383** [comment]
> #23

thanks
