### ISSUE TITLE
Shelly EM support request

### ISSUE THREAD

**Issue by Stetocasa** [produdegr/homebridge-3em-energy-meter#3]
Hi, your plug-in is fantastic
Any possibility to introduce Shelly EM support in the future?
Thanks

**Comment by produdegr** [comment]
This plugin is made for combining 3 values into one, because it is used in a 3 phase installation.
The EM has 2 meters, which usually are totally different because they meter 2 different things. So it does not make sense to take the 2 metered values and combine them. Why don't you use the "Shelly Plugin" which will at least show the values for one device.

I do not intent to make my plugin show two devices, so combining 2 ports does not make really sense. Why would you need it, please elaborate.

**Comment by Stetocasa** [comment]
> This plugin is made for combining 3 values into one, because it is used in a 3 phase installation.
> 
> The EM has 2 meters, which usually are totally different because they meter 2 different things. So it does not make sense to take the 2 metered values and combine them. Why don't you use the "Shelly Plugin" which will at least show the values for one device.
> 
> 
> 
> I do not intent to make my plugin show two devices, so combining 2 ports does not make really sense. Why would you need it, please elaborate.
> 
> 

Basically I asked to you because:

1) your shows 3 channel vs just one the Shelly plug-in
2) Shelly plug-in not supporting fakegato

**Comment by produdegr** [comment]
My plugin shows the average of 3 channels for Volt and the total for Ampere and Consumption.
If you want really 2 channels combined like that I can give it a try, but I think voltage or amperage is not supported in EM.
AS I do not have an EM, please do a http://192.168.1.1/status? (replace the IP to your) and post it here.

**Comment by Stetocasa** [comment]
{"wifi_sta":{"connected":true,"ssid":"Nino 2,4","ip":"192.168.178.176","rssi":-44},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"08:16","unixtime":1627452993,"serial":9287,"has_update":true,"mac":"8CAAB55E16D2","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":true,"source":"input"}],"emeters":[{"power":192.84,"reactive":-292.95,"voltage":237.60,"is_valid":true,"total":223691.9,"total_returned":3.3},{"power":4.98,"reactive":-26.97,"voltage":237.60,"is_valid":true,"total":11733.6,"total_returned":0.0}],"update":{"status":"pending","has_update":true,"new_version":"20210720-190643/v1.11.0-g6abd92e","old_version":"20210429-102232/v1.10.4-g3f94cd7"},"ram_total":49648,"ram_free":33236,"fs_size":233681,"fs_free":156624,"ping_check":true,"uptime":224799}

**Comment by produdegr** [comment]
Please try out V1.1.0
You must set use_em flag to true and then you can choose with use_em_mode = n (n is: 0=combine channel1 and channel2, 1 is use only channel1 and 2 use only channel2).
Please test and reply.

**Comment by Stetocasa** [comment]
Do you know how change cost parameter ? (kWh) I not found in Shelly app

**Comment by produdegr** [comment]
The Cost parameter is a EVE app thing. In the EVE app go to Settings -> General -> Energy Cost. After that you get the cost functionality in the EVE app.
