### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by marmitol** [produdegr/homebridge-3em-energy-meter#5]
I have a query, in the app it shows Total Cost Projected Cost, where do you get the electricity tariffs to provide this values? Thank you.

**Comment by produdegr** [comment]
The Cost parameter is a EVE app thing. In the EVE app go to Settings -> General -> Energy Cost. After that you get the cost functionality in the EVE app.

**Comment by marmitol** [comment]
Thanks
