### ISSUE TITLE
Solar Panels Energy Meter

### ISSUE THREAD

**Issue by bmpalmeida** [produdegr/homebridge-3em-energy-meter#6]
I'me using one channel of Shelly EM to measure the production of a solar panel system.

But i'm getting the following error:

[10/30/2021, 4:53:34 PM] [homebridge-3em-energy-meter] This plugin generated a warning from the characteristic 'Consumption': characteristic was supplied illegal value: number -34.14 exceeded minimum of 0. See https://git.io/JtMGR for more info.

It makes sense that eve app needs to have positive values, any change that you include in a config like a solar panel flag that transforms the value in positive? so it can show in the app?

**Comment by produdegr** [comment]
I can set all output to absolute values, so that the error goes away.
However, there will be no indication in Homekit if the shown value is positive or negative (i could note in the logs).

If you want this it's not too difficult to do and I can implement it within next week,

**Comment by produdegr** [comment]
Version V1.1.2 does return only absolute values, so no errors anymore. Please test.

**Comment by bmpalmeida** [comment]
I'm running it since yesterday, and its stable, and the values are correct.

Thanks very much for the addition, i can now have all the information about consumption :)
