### ISSUE TITLE
Shelly 1pm

### ISSUE THREAD

**Issue by djrams10** [produdegr/homebridge-3em-energy-meter#7]
Hello, I would like to know if it is possible to have Shelly 1pm integrated with your product because it also uses the consumption measurement of the devices connected to it. Thank you in advance for your work.

**Comment by produdegr** [comment]
Please do a http://192.168.1.1/status? (replace the IP to your shelly 1PM) and post it here.

**Comment by djrams10** [comment]
{"wifi_sta":{"connected":true,"ssid":"AirPort","ip":"192.168.86.40","rssi":-49},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"18:44","unixtime":1636998293,"serial":2257,"has_update":false,"mac":"84CCA8B13795","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"source":"input"}],"meters":[{"power":455.85,"overpower":0.00,"is_valid":true,"timestamp":1637001893,"counters":[454.622, 452.746, 451.826],"total":145827}],"inputs":[{"input":0,"event":"","event_cnt":0}],"temperature":38.73,"overtemperature":false,"tmp":{"tC":38.73,"tF":101.71, "is_valid":true},"temperature_status":"Normal","ext_sensors":{},"ext_temperature":{},"ext_humidity":{},"update":{"status":"idle","has_update":false,"new_version":"20211109-130756/v1.11.7-g682a0db","old_version":"20211109-130756/v1.11.7-g682a0db"},"ram_total":50472,"ram_free":37412,"fs_size":233681,"fs_free":149345,"uptime":98544}


Thanks

**Comment by djrams10** [comment]
It’s possible for you? Thanks

**Comment by produdegr** [comment]
No unfortunately not possible, its only returning power, whereas I need also Ampere, Voltage and Total Power.
3EM provide all, 2EM if I remember does not provide Ampere (but I calculate it).
But with only power, there is not reason to adopt this plugin, sorry. The shelly plugin already supports the shellly 1PM, why not ask for the fakegato graph implementation from them.
