### ISSUE TITLE
Device not supported

### ISSUE THREAD

**Issue by bmpalmeida** [produdegr/homebridge-3em-energy-meter#9]
Hello,

i don't know if anyone else has the same issue, the plugin is working perfectly, but i have one tricky issue in the home app.

The device appear in the favourites, and since it is not supported i don't have any way to remove it from the favourites, has anyone manage to remove it?

![IMG_5080](https://user-images.githubusercontent.com/11923453/148991094-5e4f6391-0d96-4f9e-9d5a-2c4330bacaa2.PNG)

**Comment by produdegr** [comment]
When adding new devices to homekit it asks you if you want them on the "Home" section (show status or so). So you could remove the device from homekit and add it again.

**Comment by bmpalmeida** [comment]
Mine never asks, maybe they change it.
